# Generated by Django 2.2.6 on 2020-11-02 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('author', models.CharField(blank=True, max_length=100)),
                ('pub_date', models.IntegerField()),
                ('isbn_num', models.CharField(max_length=13)),
                ('pages_amount', models.IntegerField()),
                ('link', models.URLField(max_length=300)),
                ('pub_language', models.CharField(max_length=30)),
            ],
        ),
    ]
