# Generated by Django 3.1.2 on 2020-10-29 20:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20201029_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 29, 20, 6, 32, 897967, tzinfo=utc)),
        ),
    ]
