# Generated by Django 2.2.6 on 2020-11-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20201102_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn_num',
            field=models.CharField(max_length=30),
        ),
    ]
