# Generated by Django 2.2.6 on 2020-11-02 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_auto_20201102_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='link',
            field=models.CharField(max_length=300),
        ),
    ]
