# Generated by Django 3.1.3 on 2020-11-30 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_auto_20201102_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='link',
            field=models.URLField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='book',
            name='pub_date',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='book',
            name='pub_language',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
