# Generated by Django 3.1.3 on 2020-11-30 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_auto_20201130_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn_num',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='link',
            field=models.URLField(max_length=300),
        ),
        migrations.AlterField(
            model_name='book',
            name='pub_date',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='book',
            name='pub_language',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
