# Generated by Django 3.1.3 on 2020-11-30 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_auto_20201130_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn_num',
            field=models.CharField(max_length=30),
        ),
    ]
