# Generated by Django 3.1.3 on 2020-12-03 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_auto_20201130_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn_num',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
