# Generated by Django 3.1.3 on 2020-12-05 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0014_auto_20201205_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='Rowling', max_length=100),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
